### ISSUE TITLE
Ignore PRs generated by BOTs by default

### ISSUE THREAD

**Issue by thomastvedt** [vendanor/VnKubePreviewAction#11]
Currently all PRs gets a preview. We should disable previews for PRs generated by bots. I think there is a env variable in github context isBot or something..

**Comment by ralftar** [comment]
If we stick to security updates for js, dependabot won't be so aggressive. It might be sufficient for now.

**Comment by thomastvedt** [comment]
That definitely helps!
Also, now we got a wildcard certificate in place for `*.pr.st.vendanor.com` which solves my concern about reaching the max 50 certificates per week letsencrypt rate limit.
I checked, and the preview pods doesn't consume much resources, I don't think that will be a problem.

I'm closing this 👍🏼
