### ISSUE TITLE
Add support for wildcard certificate

### ISSUE THREAD

**Issue by ralftar** [vendanor/VnKubePreviewAction#8]
Add support for wildcard certificate. *.pr.st.vendanor.com
We'll hit the max limit of 50 certificates per week soon.. 
also dependabot..

---

Noticed that the certificate existed after closing a PR.

Will it be cleanup? Does it need cleanup? E.g. creating a lot of certificates that needs renewing, or that might fail renewing.

![image](https://user-images.githubusercontent.com/1395569/105545948-fcef7e80-5cfc-11eb-8282-6b9f3409301b.png)

**Comment by thomastvedt** [comment]
Seems like you're right.
kubectl get secret --all-namespaces

![image](https://user-images.githubusercontent.com/4746639/105573780-41f8cc80-5d60-11eb-9b4d-0729c7422db7.png)


There is also possibly another solution.. I think we can request wildcard certificates from lets encrypt. The rate limit is 50 certificates per week, I don't think we'll have more than 50 PRs per week. Setting this up seemed a bit complicated and will take some time; todo or not todo ? ;)

**Comment by ralftar** [comment]
Yes, rather spend time on wildcard than spend time on creating a solution that removed old certificates

**Comment by thomastvedt** [comment]
We'll add wildcard cert .

Question:
When issuing certificates we get two "objects" in Kubernetes, `Certificate` and `Secret`. If a certificate is created by a Helm release, the certificate is deleted when the helm release is uninstalled. However secrets are not removed by cert-manager. See this link: https://cert-manager.io/docs/usage/certificate/#cleaning-up-secrets-when-certificates-are-deleted

I think this behaviour is fine. It's better to have valid certificates(secrets) "lying around", than suddenly missing a certificate, perhaps reaching letsencrypts renewal rate limit. It is possible to set the `--enable-certificate-owner-ref` when setting up cert-manager in production, but I don't see the need. What do you think?
