### ISSUE TITLE
Clean up deleted packages from registey

### ISSUE THREAD

**Issue by ralftar** [vendanor/VnKubePreviewAction#9]
It should delete packages after a PR is closed.

**Comment by thomastvedt** [comment]
Good point 👍🏼  
note to self:
https://github.com/helm/chartmuseum
https://helm.kube.vendanor.com/
GET /api/charts/<name> - list all versions of a chart
DELETE /api/charts/<name>/<version> - delete a chart version (and corresponding provenance file)

**Comment by thomastvedt** [comment]
Note that it is also possible to use VnKubePreview without uploading preview charts to chartmuseum at all. 
If `helm-repo-url` is left blank, then preview helm charts will only be generated locally in github action runner and deployed to k8s. This is probable fine in most cases, the only exception is if we want to deploy a release candidate manually or to another cluster.
